name: root
dependencies:
  - python=3.4
  - pymongo=2.8
  - nose
  - flask
  - requests
  - cssselect
  - docopt
  - boto3
  - node
  - gunicorn
  - pip:
    - mongoengine
    - flask-mongoengine
    - flask-testing
    - click
    - flask-api
    - flask-stormpath
    - hurry.filesize
    - uwsgi
    - flask-restful-swagger
    - simplejson
